changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🔥 Breaking Changes
      labels:
        - breaking-change
    - title: 🐼 Exciting New Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🎨 User Interface
      labels:
        - ux
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 🛠 Other Changes
      labels:
        - "*"
