title: Panda CMS
description: User and developer documentation for Panda CMS
theme: just-the-docs

url: https://docs.pandacms.io

aux_links:
  Template Repository: https://github.com/pandacms/panda_cms
