title: Panda CMS
description: User and developer documentation for Panda CMS
theme: just-the-docs

domain: docs.pandacms.io
url: https://docs.pandacms.io
baseurl: /docs

aux_links:
  Template Repository: https://github.com/pandacms/panda_cms
