source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "just-the-docs", "0.10.0" # pinned to the current release
# gem "just-the-docs"        # always download the latest release
